const INSERT_NOTE = 'INSERT_NOTE';
const EDIT_NOTE = 'EDIT_NOTE';
const DELETE_NOTE = 'DELETE_NOTE';
const SET_FORM_NOTE = 'SET_FORM_NOTE';

const SET_APP_SETTING = 'SET_APP_SETTING';

export {
    INSERT_NOTE,
    EDIT_NOTE,
    DELETE_NOTE,
    SET_FORM_NOTE,
    SET_APP_SETTING
};
